# --- Remove-StaleProfiles.ps1 ---
# Deletes the stale user profiles detected by StaleProfileCleanUp.ps1
# -------------------------------------------------------------

# Load the latest report (generated by detection script)
$latestReport = Get-ChildItem "C:\ProgramData\StaleProfiles_*.csv" | Sort-Object LastWriteTime -Descending | Select-Object -First 1

if (-not $latestReport) {
    Write-Host "No stale profile report found. Run StaleProfileCleanUp.ps1 first."
    exit 0
}

$profiles = Import-Csv $latestReport.FullName

# Log file for deletion actions
$logFile = "C:\ProgramData\StaleProfileCleanup\cleanup_{0:yyyyMMdd_HHmmss}.log" -f (Get-Date)
New-Item -ItemType Directory -Force -Path "C:\ProgramData\StaleProfileCleanup" | Out-Null

foreach ($p in $profiles) {
    try {
        # Remove local user account
        cmd /c "net user $($p.UserName) /delete"
        # Remove profile folder
        if (Test-Path $p.Path) {
            Remove-Item -LiteralPath $p.Path -Recurse -Force -ErrorAction SilentlyContinue
        }
        Add-Content -Path $logFile -Value "Deleted: $($p.UserName) ($($p.Path))"
        Write-Host "Deleted: $($p.UserName)"
    } catch {
        Add-Content -Path $logFile -Value "Failed: $($p.UserName) - $($_.Exception.Message)"
        Write-Host "Failed to delete $($p.UserName): $($_.Exception.Message)"
    }
}

Write-Host "Cleanup complete. Log saved to: $logFile"
